[package]
name = "color"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.82"
getrandom = { version = "0.2.7", features = ["js"] }
rand = {version = "0.8.5"}